# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d87e6bf9708e477ebb354e37aeacefe9"
name = "Cartmade Recommendation"
handle = "cartmade-recommendation"
application_url = "https://minimal-require-toys-greenhouse.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "srizn-test-store-009.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_product_listings,read_products,write_content,write_products"

[auth]
redirect_urls = [
  "https://minimal-require-toys-greenhouse.trycloudflare.com/auth/callback",
  "https://minimal-require-toys-greenhouse.trycloudflare.com/auth/shopify/callback",
  "https://minimal-require-toys-greenhouse.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
